---
abstract: 'abstract base class for both client and worker'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Fatal: '0'
  Test::HexString: '0'
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Protocol-Gearman
provides:
  Net::Gearman:
    file: lib/Net/Gearman.pm
    version: '0.02'
  Net::Gearman::Client:
    file: lib/Net/Gearman/Client.pm
    version: '0.02'
  Net::Gearman::Worker:
    file: lib/Net/Gearman/Worker.pm
    version: '0.02'
  Protocol::Gearman:
    file: lib/Protocol/Gearman.pm
    version: '0.02'
  Protocol::Gearman::Client:
    file: lib/Protocol/Gearman/Client.pm
    version: '0.02'
  Protocol::Gearman::Worker:
    file: lib/Protocol/Gearman/Worker.pm
    version: '0.02'
requires:
  Future: '0'
  IO::Socket::IP: '0'
  Struct::Dumb: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.02'
